name: Autotest Notes API

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Build application
        run: npm run build

      - name: Set fixed port
        run: echo "PORT=3395" >> $GITHUB_ENV

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to be ready..."
          while ! curl -s http://localhost:3395/notes > /dev/null; do
            echo "Waiting for server to respond on /notes..."
            sleep 5
          done
          echo "Server is ready at http://localhost:3395/notes"

      - name: Run e2e tests
        run: npm run test:notes-api
        env:
          PORT: ${{ env.PORT }}
